language: python
sudo: false
matrix:
  include:
    - python: 3.5
      env:
        - TOXENV=py35
        - USECURL=dev-gnutls-gssapi-libssh2
        - USESSL=gnutls
    - python: 3.6
      env:
        - TOXENV=py36
        - USECURL=dev-gnutls-gssapi-libssh2
        - USESSL=gnutls
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install tox coveralls
script:
  - tox --recreate
after_success:
  - coveralls
